### ISSUE TITLE
 action space

### ISSUE THREAD

**Issue by crazyleeth** [akjayant/Autonomous-Driving-via-RL#1]
hello，I am learning your project these days .I appreciate it a lot. but here is a question I dont understand that  the action space is continuous instead of discrete  in the '' DQN_Discrete_drive/ver 1.0/train.py  line 184  ''.the parameter is false by default.can you help me with that?thanks.

**Comment by akjayant** [comment]
Apologies.  Change that to True. I must have corrected it but uploaded old version to git.  In ver 2.0, ver 3.0 that parameter is True only.
Thanks.
